# Neural network notes

Imagine we want to predict our score on a test (y) based on how many hours we slept and how long we studied (x).
Let's set up some training data.

In [6]:
import numpy as np

# x = (hours slept/hours studied)
X = np.array(([3,5], [5,1], [10,2]), dtype=float)

# y = score on test
y = np.array(([75], [82], [93]), dtype=float)

In [7]:
X

array([[  3.,   5.],
       [  5.,   1.],
       [ 10.,   2.]])

In [8]:
y

array([[ 75.],
       [ 82.],
       [ 93.]])

This is called a __supervised regression__ problem.

* _supervised_: examples have inputs (hours slept/hours studied) and outputs (score)
* _regression_:  we are predicting test score, which is a _continuous_ output

If we were prediciting a letter grade, it would be a __classification__ problem.

Anyway, to solve this problem, we will use an __aritificial neural network__ (ANN).

The first problem we have is that the input is in hours, but the output is a score of 100. To make sure our variables are on the same scale, let's divide each variable by the maximum for each variable.

In [9]:
X = X/np.amax(X, axis=0)
y = y/100 # Max test score is 100

In [11]:
X

array([[ 0.3,  1. ],
       [ 0.5,  0.2],
       [ 1. ,  0.4]])

In [12]:
y

array([[ 0.75],
       [ 0.82],
       [ 0.93]])

 What will our network look like? We'll have 2 inputs -- hours of sleep and hours of study, and 1 output -- $\hat{y}$.
 
We call the output $\hat{y}$ because it's an estimate of y, but not the same as y.

The layers inbetween these inputs and outputs are __hidden layers__.

We'll use 1 hidden layer with 3 neurons.

![title](images/neuralnet.jpg)